apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
# Jaeger Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
    component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: all-in-one
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.50
          imagePullPolicy: IfNotPresent
          ports:
            - name: zipkin
              containerPort: 9411
              protocol: TCP
            - name: jaeger-collector-grpc
              containerPort: 14250
              protocol: TCP
            - name: jaeger-collector-http
              containerPort: 14268
              protocol: TCP
            - name: jaeger-query
              containerPort: 16686
              protocol: TCP
            - name: admin
              containerPort: 14269
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: JAEGER_AGENT_HOST
              value: "localhost"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SPAN_STORAGE_TYPE
              value: "badger"  # Use "elasticsearch" for production
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: BADGER_DIRECTORY_VALUE
              value: "/badger/data"
            - name: BADGER_DIRECTORY_KEY
              value: "/badger/key"
            # For Elasticsearch backend (production):
            # - name: SPAN_STORAGE_TYPE
            #   value: "elasticsearch"
            # - name: ES_SERVER_URLS
            #   value: "http://elasticsearch:9200"
            # - name: ES_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: jaeger-secrets
            #       key: es-username
            # - name: ES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: jaeger-secrets
            #       key: es-password
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /badger
          livenessProbe:
            httpGet:
              path: /
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Gi
---
# Jaeger Service
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability
  labels:
    app: jaeger
    component: query
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      protocol: TCP
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
    component: collector
spec:
  type: ClusterIP
  ports:
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: observability
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  ports:
    - name: agent-zipkin-thrift
      port: 5775
      targetPort: 5775
      protocol: UDP
    - name: agent-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
  selector:
    app: jaeger
    component: all-in-one
---
# Ingress for Jaeger UI
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: jaeger-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: jaeger.bi-ide.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
  tls:
    - hosts:
        - jaeger.bi-ide.com
      secretName: jaeger-tls
---
# Jaeger Agent DaemonSet (for node-level collection)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: observability
  labels:
    app: jaeger-agent
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.50
          imagePullPolicy: IfNotPresent
          ports:
            - name: agent-zipkin-thrift
              containerPort: 5775
              protocol: UDP
            - name: agent-compact
              containerPort: 6831
              protocol: UDP
            - name: agent-binary
              containerPort: 6832
              protocol: UDP
            - name: admin
              containerPort: 14271
              protocol: TCP
          args:
            - --reporter.grpc.host-port=jaeger-collector:14250
            - --reporter.type=grpc
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
# ConfigMap for Jaeger sampling configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-sampling-configuration
  namespace: observability
data:
  sampling.json: |
    {
      "default_strategy": {
        "type": "probabilistic",
        "param": 0.1
      },
      "service_strategies": [
        {
          "service": "bi-ide-api",
          "type": "probabilistic",
          "param": 0.5,
          "operation_strategies": [
            {
              "operation": "/health",
              "type": "probabilistic",
              "param": 0.01
            },
            {
              "operation": "/metrics",
              "type": "probabilistic",
              "param": 0.01
            }
          ]
        },
        {
          "service": "bi-ide-worker",
          "type": "probabilistic",
          "param": 0.3
        }
      ]
    }
---
# Jaeger Operator (for production with advanced features)
# apiVersion: jaegertracing.io/v1
# kind: Jaeger
# metadata:
#   name: bi-ide-jaeger
#   namespace: observability
# spec:
#   strategy: production
#   storage:
#     type: elasticsearch
#     options:
#       es:
#         server-urls: http://elasticsearch:9200
#         username: ${ES_USERNAME}
#         password: ${ES_PASSWORD}
#   ingress:
#     enabled: true
#     hosts:
#       - jaeger.bi-ide.com
#   agent:
#     sidecar:
#       injection: true
