"""Add ERP tables - accounts products employees payroll customers suppliers

Revision ID: 12c43278ec71
Revises: 001_initial
Create Date: 2026-02-24 01:12:46.190844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '12c43278ec71'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=True),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttypedb'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_accounts_code'), 'erp_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_erp_accounts_type'), 'erp_accounts', ['type'], unique=False)
    op.create_table('erp_customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_customers_customer_code'), 'erp_customers', ['customer_code'], unique=True)
    op.create_table('erp_employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED', name='employeestatusdb'), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_erp_employees_department'), 'erp_employees', ['department'], unique=False)
    op.create_index(op.f('ix_erp_employees_employee_number'), 'erp_employees', ['employee_number'], unique=True)
    op.create_index(op.f('ix_erp_employees_status'), 'erp_employees', ['status'], unique=False)
    op.create_table('erp_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=300), nullable=False),
    sa.Column('customer_email', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatusdb'), nullable=False),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_invoices_customer_id'), 'erp_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_erp_invoices_invoice_number'), 'erp_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_erp_invoices_status'), 'erp_invoices', ['status'], unique=False)
    op.create_table('erp_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('supplier', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_products_category'), 'erp_products', ['category'], unique=False)
    op.create_index(op.f('ix_erp_products_sku'), 'erp_products', ['sku'], unique=True)
    op.create_table('erp_suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_suppliers_supplier_code'), 'erp_suppliers', ['supplier_code'], unique=True)
    op.create_table('erp_payroll_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['erp_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_payroll_records_employee_id'), 'erp_payroll_records', ['employee_id'], unique=False)
    op.create_table('erp_stock_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_stock_movements_product_id'), 'erp_stock_movements', ['product_id'], unique=False)
    op.create_table('erp_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_account_id', sa.String(), nullable=False),
    sa.Column('credit_account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['erp_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['erp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=200), nullable=True),
    sa.Column('invoice_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=500), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('email', sa.VARCHAR(length=300), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reorder_point', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('supplier', sa.VARCHAR(length=300), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=1)
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('email', sa.VARCHAR(length=300), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('department', sa.VARCHAR(length=200), nullable=True),
    sa.Column('position', sa.VARCHAR(length=200), nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=1)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('tax', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('items', sqlite.JSON(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.drop_table('erp_transactions')
    op.drop_index(op.f('ix_erp_stock_movements_product_id'), table_name='erp_stock_movements')
    op.drop_table('erp_stock_movements')
    op.drop_index(op.f('ix_erp_payroll_records_employee_id'), table_name='erp_payroll_records')
    op.drop_table('erp_payroll_records')
    op.drop_index(op.f('ix_erp_suppliers_supplier_code'), table_name='erp_suppliers')
    op.drop_table('erp_suppliers')
    op.drop_index(op.f('ix_erp_products_sku'), table_name='erp_products')
    op.drop_index(op.f('ix_erp_products_category'), table_name='erp_products')
    op.drop_table('erp_products')
    op.drop_index(op.f('ix_erp_invoices_status'), table_name='erp_invoices')
    op.drop_index(op.f('ix_erp_invoices_invoice_number'), table_name='erp_invoices')
    op.drop_index(op.f('ix_erp_invoices_customer_id'), table_name='erp_invoices')
    op.drop_table('erp_invoices')
    op.drop_index(op.f('ix_erp_employees_status'), table_name='erp_employees')
    op.drop_index(op.f('ix_erp_employees_employee_number'), table_name='erp_employees')
    op.drop_index(op.f('ix_erp_employees_department'), table_name='erp_employees')
    op.drop_table('erp_employees')
    op.drop_index(op.f('ix_erp_customers_customer_code'), table_name='erp_customers')
    op.drop_table('erp_customers')
    op.drop_index(op.f('ix_erp_accounts_type'), table_name='erp_accounts')
    op.drop_index(op.f('ix_erp_accounts_code'), table_name='erp_accounts')
    op.drop_table('erp_accounts')
    # ### end Alembic commands ###
