"""Add invoice_items table and ERP improvements

Revision ID: 2026_02_23_002
Revises: 12c43278ec71
Create Date: 2026-02-23 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_02_23_002'
down_revision: Union[str, None] = '12c43278ec71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create invoice_items table
    op.create_table('erp_invoice_items',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('invoice_id', sa.String(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['erp_invoices.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['erp_products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_invoice_items_invoice_id'), 'erp_invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_erp_invoice_items_product_id'), 'erp_invoice_items', ['product_id'], unique=False)
    
    # Add overtime column to payroll_records
    op.add_column('erp_payroll_records', sa.Column('overtime', sa.Numeric(precision=15, scale=2), nullable=True, default=0))
    
    # Add balance column to customers
    op.add_column('erp_customers', sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True, default=0))
    
    # Create foreign key for invoices.customer_id to customers.id
    # Note: This requires customer_id to reference existing customers
    # We'll create the FK without enforcing for existing data
    with op.batch_alter_table('erp_invoices') as batch_op:
        batch_op.create_foreign_key('fk_invoices_customer', 'erp_customers', ['customer_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key
    with op.batch_alter_table('erp_invoices') as batch_op:
        batch_op.drop_constraint('fk_invoices_customer', type_='foreignkey')
    
    # Drop columns
    op.drop_column('erp_customers', 'balance')
    op.drop_column('erp_payroll_records', 'overtime')
    
    # Drop invoice_items table
    op.drop_index(op.f('ix_erp_invoice_items_product_id'), table_name='erp_invoice_items')
    op.drop_index(op.f('ix_erp_invoice_items_invoice_id'), table_name='erp_invoice_items')
    op.drop_table('erp_invoice_items')
    
    # ### end Alembic commands ###
