filebeat.inputs:
# Application logs
- type: log
  enabled: true
  paths:
    - /var/log/bi-ide/api/*.log
    - /app/logs/*.log
  fields:
    service: bi-ide-api
    environment: production
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after
  exclude_files: ['\.gz$']
  ignore_older: 72h
  close_inactive: 1h

# Error logs
- type: log
  enabled: true
  paths:
    - /var/log/bi-ide/api/error*.log
  fields:
    service: bi-ide-api
    log_level: error
    environment: production
  fields_under_root: true

# Access logs (Nginx)
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    service: nginx
    log_type: access
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Audit logs
- type: log
  enabled: true
  paths:
    - /var/log/bi-ide/audit/*.log
  fields:
    service: bi-ide-audit
    log_type: audit
  fields_under_root: true

# Container logs
- type: container
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  fields:
    service: docker
  fields_under_root: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
        match_fields: ["container.image.name", "container.name"]
        match_pids: ["process.pid", "process.parent.pid"]
        match_source: true
        match_source_index: 4
        cleanup_timeout: 60
        labels.dedot: false
        env.whitelist: ["SERVICE_NAME", "ENVIRONMENT"]

# Kubernetes logs
- type: kubernetes
  enabled: false  # Enable when running in K8s
  paths:
    - /var/log/containers/*.log
  fields:
    environment: kubernetes
  fields_under_root: true
  processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        namespace: bi-ide-v8
        matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

# System logs
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/secure
  fields:
    service: system
  fields_under_root: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  worker: 2
  compression_level: 3
  bulk_max_size: 2048
  slow_start: true
  ttl: 30
  timeout: 30
  max_retries: 3

# Output to Elasticsearch (alternative)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   protocol: "https"
#   username: "${ES_USERNAME}"
#   password: "${ES_PASSWORD}"
#   index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
#   ssl:
#     verification_mode: "full"
#     certificate_authorities: ["/etc/filebeat/certs/ca.crt"]

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
      netinfo.enabled: true
      cache.ttl: 5m
      geo:
        name: dc1
        location: 40.7128, -74.0060
        continent_name: North America
        country_iso_code: US
        region_name: New York
        region_iso_code: NY
        city_name: New York

  - add_cloud_metadata:
      providers:
        - aws
        - gcp
        - azure
        - digitalocean

  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - add_kubernetes_metadata:
      in_cluster: true

  - add_labels:
      labels:
        application: bi-ide-v8
        team: platform

  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.name", "agent.type", "agent.version"]
      ignore_missing: true

  - drop_fields:
      when:
        contains:
          message: "password"
      fields: ["message"]
      ignore_missing: true

  - script:
      lang: javascript
      id: parse_timestamp
      source: >
        function process(event) {
          var message = event.Get("message");
          if (message && message.startsWith("{")) {
            try {
              var parsed = JSON.parse(message);
              if (parsed.timestamp) {
                event.Put("@timestamp", parsed.timestamp);
              }
              if (parsed.level) {
                event.Put("log.level", parsed.level.toLowerCase());
              }
            } catch(e) {}
          }
        }

  - fingerprint:
      fields: ["@timestamp", "message", "host.name"]
      target_field: "@metadata._id"
      method: "sha256"
      ignore_missing: false

# Queue settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s

# Disk queue (for high throughput)
# queue.disk:
#   max_size: 10GB

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["${ES_HOST:elasticsearch:9200}"]
  username: "${ES_USERNAME:filebeat_system}"
  password: "${ES_PASSWORD}"

# Setup
setup.ilm.enabled: auto
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy_name: "filebeat-policy"
setup.ilm.policy_file: /etc/filebeat/ilm-policy.json

setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1
  index.refresh_interval: 5s
